_target_: src.datamodules.default_datamodule.DefaultDataModule

opt:
  train:
    dataset_type: GeoArtDatasetV0
    data_dir: ${data_dir} # data_dir is specified in config.yaml
    data_path:
      - syn/cabinet2_rand_train_1K
      - syn/drawer_train_1K
      - syn/microwave_train_1K
      - syn/toaster_train_1K
    num_point: 8192
    num_point_occ: 2048
    num_point_seg: 512
    norm: True
    norm_padding: 0.1
    batch_size: 32
    num_workers: 4
    rand_rot: False # random rotation of input data
    weighted_occ_sample: False

  val:
    dataset_type: GeoArtDatasetV1
    data_dir: ${data_dir} # data_dir is specified in config.yaml
    data_path:
      - syn/cabinet2_rand_val_50
      - syn/drawer_val_50
      - syn/microwave_val_50
      - syn/toaster_val_50
    num_point: 8192
    #num_point_occ: 90000
    #num_point_seg: 5000
    norm: True
    norm_padding: 0.1
    batch_size: 1
    num_workers: 4
    rand_rot: False # random rotation of input data

  test:
    dataset_type: GeoArtDatasetV1
    data_dir: ${data_dir} # data_dir is specified in config.yaml
    data_path:
      - syn/cabinet2_rand_test_standard
      - syn/drawer_test_standard
      - syn/microwave_test_standard
      - syn/toaster_test_standard
    num_point: 8192
    #num_point_occ: 90000
    #num_point_seg: 5000
    norm: True
    norm_padding: 0.1
    batch_size: 1
    num_workers: 4
    rand_rot: False # random rotation of input data
